name: Rollbar-gem CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby-version: [2.5.3, 2.6.0, 2.6.6, 2.7.2]
        gemfile:
          - gemfiles/rails50.gemfile
          - gemfiles/rails51.gemfile
          - gemfiles/rails52.gemfile
          - gemfiles/rails60.gemfile
          - gemfiles/rails61.gemfile
        include:
          - gemfile: gemfiles/rails71.gemfile
            ruby-version: 3.2.2
          - gemfile: gemfiles/rails71.gemfile
            ruby-version: 3.1.1
          - gemfile: gemfiles/rails70.gemfile
            ruby-version: 3.1.1
          - gemfile: gemfiles/rails70.gemfile
            ruby-version: 3.0.3
          - gemfile: gemfiles/rails61.gemfile
            ruby-version: 3.0.3

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 4

      - name: Setup Ruby > 2.0
        uses: ruby/setup-ruby@v1
        if: ${{ matrix.ruby-version != '2.0.0' }}
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Rails 4.2 ensure bundler version
        if: ${{ matrix.gemfile == 'gemfiles/rails42.gemfile' }}
        run: |
          gem uninstall bundler
          gem install bundler -v '< 2.0.0'

      - name: Bundle Install
        run: |
          export BUNDLE_GEMFILE=${{ matrix.gemfile }}
          bundle config path vendor/bundle
          bundle config gemfile ${{ matrix.gemfile }}
          bundle install --jobs 4 --retry 3

      - name: Rspec
        run: |
          export BUNDLE_GEMFILE=${{ matrix.gemfile }}
          bundle config path vendor/bundle
          bundle config gemfile ${{ matrix.gemfile }}
          bundle exec rspec
